[package]
name = "rust_wasm_functions"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.39", features = ["serde"] }
dotenv = "0.15.0"
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib", "rlib"]
